### ISSUE TITLE
Feature request: paste raw link

### ISSUE THREAD

**Issue by axelchalon** [jvalente/roamresearchmarkdownlinks#1]
Hi!

Thank you for this great extension; it works very well and is very handy!

I noticed there are times where I want to paste the link directly, and couldn't find a way to do this. I think it would be great to have this possibility as well! Here are some ideas:
- Paste the raw link instead of the markdown link when the cursor is already inside the URL part of a markdown link (e.g. when cursor is here between the round brackets: `My text, my [anchor](|)`)
- Or possibly have e.g. Ctrl+Shift+V paste the raw link

Thanks for your work!

**Comment by jvalente** [comment]
Hello @axelchalon, thank you very much for your contribution. 
My end of year was a bit hectic and I didn't pay much attention to GitHub notifications. During the next weekend I will take the time to take a look at the issue and your pull requests.

Will keep you posted!

Regards,
João

**Comment by jvalente** [comment]
Hello @axelchalon, I've just published version 1.6.0 that reflects all the improvements you suggested. 
Thank you very much for your contribution.

Regards,
João
